<?php

namespace Database\Factories;

use App\Models\Product;
use App\Models\ProductReview;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ProductReview>
 */
class ProductReviewFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    protected $model = ProductReview::class;
    public function definition(): array
    {

        $reviews = [
            'Great product! Highly recommended.',
            'Not worth the price. Quality is poor.',
            'Average experience, could be better.',
            'Excellent quality, would buy again!',
            'Disappointed with the customer service.',
            'Good value for money.',
            'Exceeded my expectations!',
            'Just okay, nothing special.',
            'Terrible product, do not buy!',
            'Very satisfied with my purchase.',
            'Highly recommend for tech enthusiasts.',
            'Good performance, reliable.',
            'Fast shipping and delivery.',
            'Packaging was well done.',
            'Could use more features.',
            'Nice design, sleek look.',
            'Worth every penny spent.',
            'A bit pricey, but worth it.',
            'Customer support was helpful.',
            'Shipping took longer than expected.',
            'Affordable and efficient.',
            'Perfect for daily use.',
            'Impressed by the quality.',
            'Not as advertised.',
            'Great battery life.',
            'Poor after-sales service.',
            'Works as expected.',
            'Easy to set up and use.',
            'Not user-friendly.',
            'Exceeded my expectations.',
            'Just okay, could improve.',
            'Amazing performance!',
            'Love the functionality.',
            'Disappointing performance.',
            'Sturdy and durable.',
            'Cheap build quality.',
            'Exceptional value for money.',
            'Highly recommended for professionals.',
            'Below average experience.',
            'Highly versatile product.',
            'Excellent support team.',
            'Average customer service.',
            'User interface could be improved.',
            'Satisfied with the purchase.',
            'Not durable at all.',
            'Great for beginners.',
            'Highly reliable.',
            'Good quality for the price.',
            'Not very efficient.',
            'Excellent features.',
            'A bit outdated design.',
            'Fast and smooth experience.',
            'Poor quality control.',
            'Would recommend to others.',
            'Excellent for advanced users.',
            'Needs better updates.',
            'Exceeded my expectations.',
            'Value for money.',
            'Highly recommended for tech professionals.',
            'Average product quality.',
            'Excellent service!',
            'Not worth the hype.',
            'Well packaged and delivered on time.',
            'Easy to maintain.',
            'Not very customizable.',
            'Stunning performance!',
            'Terrible customer experience.',
            'Sleek design, but fragile.',
            'Exceeded expectations with its versatility.',
            'Highly functional.',
            'Confusing interface.',
            'Affordable and reliable.',
            'Above-average performance.',
            'Decent product, could be better.',
            'Highly efficient.',
            'Poor design, not ergonomic.',
            'Worth the investment.',
            'Great value for a premium product.',
            'Highly recommend for everyday use.',
            'Average build quality.',
            'Highly innovative.',
            'Fast and responsive.',
            'Decent features for the price.',
            'Poor performance under load.',
            'Exceptional quality!',
            'Highly recommended for tech-savvy users.',
            'Affordable yet durable.',
            'Terrific product for the price.',
            'Packaging could be better.',
            'Amazing customer support!',
            'Not user-friendly at all.',
            'Highly durable and long-lasting.',
            'Above-average customer satisfaction.',
            'Good overall experience.',
            'Highly efficient for professionals.',
            'Highly recommended for beginners.',
            'Average usability.',
            'Great for experienced users.',
            'Value-for-money product.',
            'Poor performance on certain tasks.',
            'Elegant design and reliable.',
            'Highly versatile for different applications.',
            'Exceeded all my expectations.',
            'Excellent for creative professionals.',
            'Not worth the purchase.',
            'Affordable and functional.',
            'Exceptional design and build.',
            'Highly recommended for businesses.',
            'Above-average performance.',
            'Highly durable and sturdy.',
            'Affordable, yet powerful.',
            'Highly intuitive interface.',
            'Terrible battery life.',
            'Fantastic product overall!',
            'Well-built, but overpriced.',
            'Great for students and professionals.',
            'Highly recommended for casual users.',
            'Good value with decent features.',
            'Exceeded expectations with its reliability.',
            'Sleek and modern design.',
            'Average product, lacks advanced features.',
            'Highly efficient for multitasking.',
            'Highly recommended for small businesses.',
            'Affordable, yet feature-rich.',
            'Exceptional performance for high demands.',
            'Highly recommend for tech professionals.',
            'Not user-friendly for beginners.',
            'Terrific product, highly recommended.',
            'Affordable and efficient.',
            'Above-average customer support.',
            'Highly functional for various tasks.',
            'Average product, could improve.',
            'Highly efficient under pressure.',
            'Good build quality, but lacks features.',
            'Highly recommended for creative professionals.',
            'Exceptional build quality and performance.',
            'Highly recommended for tech enthusiasts.',
            'Affordable and highly versatile.',
            'Fantastic customer service!',
            'Not very reliable under stress.',
            'Highly recommended for professionals.',
            'Exceptional product performance.',
            'Above-average usability.',
            'Highly recommended for beginners.',
            'Highly durable and long-lasting.',
            'Great for general use.',
            'Affordable, yet premium quality.',
            'Highly innovative and reliable.',
            'Great for home and office use.',
            'Highly efficient for multitasking.',
            'Above-average performance, great price.',
            'Highly recommended for businesses.',
            'Great for high-demand environments.',
            'Highly versatile for different applications.',
            'Exceeded expectations with its features.',
            'Highly durable, perfect for heavy usage.',
            'Great value for professional use.',
            'Highly recommended for tech-savvy users.',
            'Well-designed and functional.',
            'Highly efficient for professionals.',
            'Above-average product quality.',
            'Highly reliable for long-term use.',
            'Excellent product for professionals.',
            'Highly recommended for casual users.',
            'Good performance, needs improvements.',
            'Highly durable and robust.',
            'Exceptional quality for the price.',
            'Highly recommended for tech professionals.',
            'Affordable and efficient.',
            'Above-average performance, reasonable price.',
            'Highly versatile and efficient.',
            'Exceeded expectations with its functionality.',
            'Exceptional design and build.',
            'Highly recommended for businesses.',
            'Fantastic support and usability.',
            'Highly recommended for beginners.',
            'Affordable and highly efficient.',
            'Exceptional reliability and performance.',
            'Highly recommended for professionals.',
            'Great for everyday tasks.',
            'Highly durable and long-lasting.',
            'Affordable, yet powerful.',
            'Highly intuitive and user-friendly.',
            'Terrific product for the price.',
            'Exceptional customer service!',
            'Highly recommended for small businesses.',
            'Highly efficient under pressure.',
            'Above-average usability, excellent features.',
            'Highly recommended for creative professionals.',
            'Affordable and feature-rich.',
            'Exceptional product performance.',
            'Highly durable and sturdy.',
            'Highly recommended for tech-savvy users.',
            'Good build quality, but lacks features.',
            'Highly efficient for multitasking.',
            'Highly recommended for professionals.',
            'Above-average performance, great price.',
            'Highly versatile for different applications.',
            'Exceeded expectations with its features.',
            'Highly durable, perfect for heavy usage.',
            'Great value for professional use.',
            'Highly recommended for tech enthusiasts.',
            'Well-designed and functional.',
            'Highly efficient for professionals.',
            'Above-average product quality.',
            'Highly reliable for long-term use.',
            'Excellent product for professionals.',
            'Highly recommended for casual users.',
            'Good performance, needs improvements.',
            'Highly durable and robust.',
            'Exceptional quality for the price.',
            'Highly recommended for tech professionals.',
            'Affordable and efficient.',
            'Above-average performance, reasonable price.',
            'Highly versatile and efficient.',
            'Exceeded expectations with its functionality.',
            'Exceptional design and build.',
            'Highly recommended for businesses.',
            'Fantastic support and usability.',
            'Highly recommended for beginners.',
            'Affordable and highly efficient.',
            'Exceptional reliability and performance.',
            'Highly recommended for professionals.',
            'Great for everyday tasks.',
            'Highly durable and long-lasting.',
            'Affordable, yet powerful.',
            'Highly intuitive and user-friendly.',
            'Terrific product for the price.',
            'Exceptional customer service!',
            'Highly recommended for small businesses.',
            'Highly efficient under pressure.',
            'Above-average usability, excellent features.',
            'Highly recommended for creative professionals.',
            'Affordable and feature-rich.',
            'Exceptional product performance.',
            'Highly durable and sturdy.',
            'Highly recommended for tech-savvy users.',
            'Good build quality, but lacks features.',
            'Highly efficient for multitasking.',
            'Highly recommended for professionals.',
            'Above-average performance, great price.',
            'Highly versatile for different applications.',
            'Exceeded expectations with its features.',
            'Highly durable, perfect for heavy usage.',
            'Great value for professional use.',
            'Highly recommended for tech enthusiasts.',
            'Well-designed and functional.',
            'Highly efficient for professionals.',
            'Above-average product quality.',
            'Highly reliable for long-term use.',
            'Excellent product for professionals.',
            'Highly recommended for casual users.',
            'Good performance, needs improvements.',
            'Highly durable and robust.',
            'Exceptional quality for the price.',
            'Highly recommended for tech professionals.',
            'Affordable and efficient.',
            'Above-average performance, reasonable price.',
            'Highly versatile and efficient.',
            'Exceeded expectations with its functionality.',
            'Exceptional design and build.',
            'Highly recommended for businesses.',
            'Fantastic support and usability.',
            'Highly recommended for beginners.',
            'Affordable and highly efficient.',
            'Exceptional reliability and performance.',
            'Highly recommended for professionals.',
            'Great for everyday tasks.',
            'Highly durable and long-lasting.',
            'Affordable, yet powerful.',
            'Highly intuitive and user-friendly.',
            'Terrific product for the price.',
            'Exceptional customer service!',
            'Highly recommended for small businesses.',
            'Highly efficient under pressure.',
            'Above-average usability, excellent features.',
            'Highly recommended for creative professionals.',
            'Affordable and feature-rich.',
            'Exceptional product performance.',
            'Highly durable and sturdy.',
            'Highly recommended for tech-savvy users.',
            'Good build quality, but lacks features.',
            'Highly efficient for multitasking.',
            'Highly recommended for professionals.',
            'Above-average performance, great price.',
            'Highly versatile for different applications.',
            'Exceeded expectations with its features.',
            'Highly durable, perfect for heavy usage.',
            'Great value for professional use.',
            'Highly recommended for tech enthusiasts.',
            'Well-designed and functional.',
            'Highly efficient for professionals.',
            'Above-average product quality.',
            'Highly reliable for long-term use.',
            'Excellent product for professionals.',
            'Highly recommended for casual users.',
            'Good performance, needs improvements.',
            'Highly durable and robust.',
            'Exceptional quality for the price.',
            'Highly recommended for tech professionals.',
            'Affordable and efficient.',
            'Above-average performance, reasonable price.',
            'Highly versatile and efficient.',
            'Exceeded expectations with its functionality.',
            'Exceptional design and build.',
            'Highly recommended for businesses.',
            'Fantastic support and usability.',
            'Highly recommended for beginners.',
            'Affordable and highly efficient.',
            'Exceptional reliability and performance.',
            'Highly recommended for professionals.',
            'Great for everyday tasks.',
            'Highly durable and long-lasting.',
            'Affordable, yet powerful.',
            'Highly intuitive and user-friendly.',
            'Terrific product for the price.',
            'Exceptional customer service!',
            'Highly recommended for small businesses.',
            'Highly efficient under pressure.',
            'Above-average usability, excellent features.',
            'Highly recommended for creative professionals.',
            'Affordable and feature-rich.',
        ];
        
        return [
            'product_id' => Product::factory(), 
            'rating' => $this->faker->numberBetween(1, 5),  // Realistic rating between 1 and 5
            'sentiment_type' => $this->faker->randomElement(['positive', 'negative', 'neutral']),  
            'review' => $this->faker->randomElement($reviews),  // Using random review from predefined array
        ];
    }
}
