<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;
use App\Models\Review;
/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Review>
 */
class ReviewFactory extends Factory
{

    protected $model = Review::class;

    // Predefined array of sample review texts
    protected $sampleReviews = [
        "This product exceeded my expectations!",
        "I had a great experience with this product.",
        "The quality is outstanding, will buy again!",
        "Not worth the price; I expected better quality.",
        "It was okay, but I wouldn't recommend it to a friend.",
        "Fantastic service and great product!",
        "I received a defective item, but customer service was helpful.",
        "This is my favorite purchase of the year!",
        "It does what it says, but nothing extraordinary.",
        "I love this! Highly recommend to everyone.",
        "The product arrived on time and in perfect condition.",
        "Really happy with my purchase, worth every penny!",
        "I've bought this item multiple times; it's a must-have!",
        "The design is beautiful, and it works perfectly.",
        "It didn't meet my expectations, but it's still decent.",
        "One of the best purchases I've made this year!",
        "It's good, but there are better alternatives available.",
        "I was pleasantly surprised by how well it performs.",
        "The instructions were unclear, but I managed to figure it out.",
        "Amazing quality for the price! Will buy again.",
        "I had to return it; it wasn't what I expected.",
        "It's not bad, but I've seen better.",
        "The color was different from what I expected, but I like it.",
        "Delivery took longer than expected, but the product is nice.",
        "Absolutely love this product; it's changed my life!",
        "It's fine for casual use but not for serious needs.",
        "Very sturdy and well-made, I highly recommend it.",
        "I was disappointed with the size; it was smaller than advertised.",
        "Great features, but the battery life is too short.",
        "This product has great reviews, but I didn't see the hype.",
        "Sleek design and easy to use; I'm very satisfied.",
        "I won't buy this again, as I had a bad experience.",
        "Great product, but the price is a bit high for my budget.",
        "The taste is fantastic; I'm definitely buying more!",
        "It's okay, but I expected more based on the description.",
        "Impressive results! This is now a staple in my home.",
        "I love the versatility of this product; it's so handy!",
        "The customer service was unresponsive, which was frustrating.",
        "This is exactly what I needed; it works perfectly!",
        "Not bad, but it took longer to see results than expected.",
        "I'm so glad I bought this; it's worth every dollar!",
        "It's a decent product, but I think I can find better options.",
        "This product is a game changer; I can’t imagine my life without it!",
        "While the product is good, I found it difficult to use at first.",
        "Great quality for the price!",
        "I’ve had better products for less money.",
        "This exceeded all my expectations.",
        "I’ll definitely buy this again!",
        "Perfect for what I needed.",
        "The instructions were a bit confusing.",
        "The item arrived damaged; very disappointing.",
        "High quality and great value for money.",
        "Not what I expected at all.",
        "Fantastic! I love it!",
        "I would not recommend this to anyone.",
        "The performance is incredible!",
        "It has some flaws, but overall it’s good.",
        "It's beautiful, but I had issues with it.",
        "I’m very satisfied with my purchase.",
        "This is a must-have for anyone!",
        "Great design, but functionality is lacking.",
        "This item really delivers!",
        "The size was too small for my needs.",
        "I expected a higher quality product.",
        "The product looks nice but doesn’t work well.",
        "Very convenient and easy to use.",
        "This product is just okay.",
        "I am very pleased with this purchase.",
        "It's everything I wanted and more.",
        "I was not impressed with this product.",
        "Great buy, highly recommend!",
        "It has some good features but lacks others.",
        "Overall, a good product.",
        "Amazing! Highly recommend it!",
        "Very functional and easy to use.",
        "It does not match the description.",
        "I'm happy with the quality of this product.",
        "It performs well, but there are better options.",
        "Decent product, but overpriced.",
        "It’s not bad but could be improved.",
        "I will be buying this again.",
        "Excellent quality, very satisfied!",
        "This is not what I expected.",
        "The product works great, very happy!",
        "It's a nice product, but not for me.",
        "I would purchase this again in a heartbeat!",
        "The packaging was a bit disappointing.",
        "Not what I hoped for.",
        "I love how this works!",
        "This has become my new favorite!",
        "It's a good product, but I had high expectations.",
        "I’m really pleased with how this performs.",
        "This product is just what I needed.",
        "I had an issue with it, but it was resolved quickly.",
        "Very effective, just what I wanted.",
        "A little pricey for what it is.",
        "It’s okay, but I wouldn’t buy it again.",
        "Great product for the price!",
        "Not as good as I thought it would be.",
        "I am thrilled with this purchase!",
        "The product is good, but the delivery was slow.",
        "It’s not worth the hype.",
        "Very useful and practical.",
        "This product has changed my routine for the better.",
        "It looks nice but doesn’t perform well.",
        "I’m impressed with the quality!",
        "It’s not perfect but gets the job done.",
        "Great for the price, highly recommend!",
        "I wouldn’t recommend this product.",
        "The functionality is excellent.",
        "It's a solid product overall.",
        "I wish I had bought this sooner!",
        "Disappointed with my purchase.",
        "I love this product; it’s amazing!",
        "It’s just okay, nothing special.",
        "The quality is subpar for the price.",
        "Great product, but poor customer service.",
        "I’m very happy with my purchase!",
        "This product is fantastic!",
        "The color is not as described.",
        "I think this product is overpriced.",
        "It does what it says, no complaints!",
        "This product is mediocre at best.",
        "Highly recommended! You won’t regret it.",
        "Not a fan; it didn’t meet my expectations.",
        "Fantastic quality, worth every penny!",
        "It arrived late, which was disappointing.",
        "This is a must-have item!",
        "It works well, but I wish it had more features.",
        "I'm very impressed with this product!",
        "This didn’t live up to the reviews.",
        "It has a nice design but lacks functionality.",
        "Great service, great product!",
        "I have no complaints about this item.",
        "This is just what I was looking for!",
        "It’s fine, but I’ve seen better.",
        "This product works great for my needs.",
        "I’m not happy with this purchase.",
        "The design is sleek and modern.",
        "Very practical and easy to store.",
        "I had to return it; it was defective.",
        "I wish I had read the reviews before buying.",
        "Great value for the price!",
        "This is my go-to product now.",
        "The quality could be better.",
        "The product is okay, but not great.",
        "I’m so happy with this purchase!",
        "Very versatile and useful.",
        "I was let down by this product.",
        "Great experience overall.",
        "This item exceeded my expectations!",
        "It was okay, but not what I was hoping for.",
        "Fantastic product, highly recommend!",
        "The quality is exceptional.",
        "I will definitely buy this again!",
        "Not impressed with the quality.",
        "This is one of the best purchases I’ve made.",
        "I’m very disappointed with this product.",
        "Excellent value for the money!",
        "I would not purchase this again.",
        "This product works as advertised.",
        "Great for everyday use.",
        "It’s very user-friendly!",
        "This was a waste of money.",
        "Great product, very satisfied!",
        "I had high hopes, but it fell flat.",
        "I love how it looks and performs.",
        "It’s not what I expected.",
        "Fantastic quality and service!",
        "Very easy to use and effective.",
        "I had to contact customer service, and they were helpful.",
        "I’m so glad I bought this!",
        "Not worth the money.",
        "This product is a game-changer!",
        "Very well made and sturdy.",
        "I’m not a fan; I prefer other brands.",
        "I appreciate the quality of this item.",
        "It’s okay, but I’ve seen better.",
        "I’m very satisfied with my purchase.",
        "Great product, would recommend to friends!",
        "It arrived quickly, which was a plus.",
        "This has become a staple in my home.",
        "The performance is just average.",
        "This product is wonderful!",
        "It’s good for beginners.",
        "I wouldn’t recommend it for experienced users.",
        "It works perfectly for me!",
        "This is a nice addition to my collection.",
        "It looks great on my shelf!",
        "I’ve had issues with it not working.",
        "Very happy with my choice!",
        "I wish it was easier to use.",
        "Excellent product, highly recommend!",
        "Not suitable for my needs.",
        "This is a fantastic value for money.",
        "I expected better performance.",
        "This is a solid choice for anyone.",
        "I’ll definitely be purchasing again.",
        "I didn’t find it useful.",
        "Great product, very effective!",
        "I wish I had done more research.",
        "This product has a sleek design.",
        "I’m a little disappointed in the size.",
        "Works great, no issues!",
        "Not a great product for the price.",
        "Very happy with the quality!",
        "It’s not as good as I thought it would be.",
        "Amazing product! Highly recommend it.",
        "It’s a decent product but could be improved.",
        "Good product for the price!",
        "I expected more from this brand.",
        "This is exactly what I needed!",
        "Very convenient and useful.",
        "I’m so pleased with my purchase!",
        "The product works as intended.",
        "This has been a great addition to my home.",
        "I wasn’t impressed with the functionality.",
        "Very happy with the service and product.",
        "This product is fantastic!",
        "I had a bad experience with the delivery.",
        "It’s okay, but there are better options.",
        "Great for the price, very effective!",
        "I will buy this product again.",
        "It’s nice, but I wish it were bigger.",
        "The product is just okay.",
        "I had high expectations, but it fell short.",
        "Excellent purchase, very satisfied!",
        "The quality is not up to par.",
        "This is a great product overall.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected at all.",
        "I love how this product works!",
        "Great product, I use it every day.",
        "The price is a bit high for my budget.",
        "This is my new favorite item!",
        "I wouldn’t recommend this to a friend.",
        "Very useful and practical for my needs.",
        "Great purchase! Highly recommend.",
        "It arrived late, but it was worth the wait.",
        "This product is just what I needed.",
        "It’s okay, but not the best.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "The customer service was excellent.",
        "I had high hopes, but this product did not deliver.",
        "Great features and very functional.",
        "I was surprised by the quality!",
        "Not as good as I thought it would be.",
        "This is an excellent product, highly recommended.",
        "Very convenient, I use it daily.",
        "I’m not impressed with the performance.",
        "Fantastic product! I’ll buy again.",
        "It’s just okay, nothing special.",
        "Very sturdy and well made.",
        "Great quality and design!",
        "I’m really happy with my purchase.",
        "This product is worth the investment.",
        "I wouldn’t buy this again.",
        "Great value for the price!",
        "I’ve seen better products for less money.",
        "Amazing product! Highly recommended.",
        "Not worth the hype.",
        "Very satisfied with this purchase!",
        "This product is just what I was looking for.",
        "It’s not the best but it gets the job done.",
        "I love the design and functionality.",
        "It’s okay, but not my favorite.",
        "I will definitely buy this again!",
        "Not what I expected.",
        "I’m very happy with this item.",
        "Great performance and quality!",
        "I had an issue, but it was resolved quickly.",
        "This product exceeded my expectations!",
        "Very functional and easy to use.",
        "The color is different from what I expected.",
        "I’m disappointed with the quality.",
        "This is a great product for the price!",
        "I wish it had more features.",
        "Great experience overall!",
        "I would recommend this to others.",
        "Fantastic product! Highly recommend.",
        "It didn’t live up to the reviews.",
        "I had a great experience with this product.",
        "The instructions were confusing.",
        "This is an excellent purchase!",
        "Not a great fit for my needs.",
        "Great quality! I’m very satisfied.",
        "The performance is mediocre.",
        "I had to return it; it was defective.",
        "Very happy with my purchase.",
        "This is a fantastic product!",
        "The price is a bit steep.",
        "I’m impressed with the quality!",
        "It does not match the description.",
        "Great buy! Highly recommend.",
        "It’s okay, but I wouldn’t buy it again.",
        "I love how this works!",
        "Not what I was hoping for.",
        "Very effective and easy to use.",
        "The product looks nice, but it has flaws.",
        "I was surprised by the quality!",
        "Great value for the price!",
        "I would not purchase this again.",
        "Fantastic product! I’ll buy again.",
        "This is exactly what I needed.",
        "I had a good experience overall.",
        "The customer service was excellent!",
        "I’m not satisfied with this product.",
        "Great for the price, very effective.",
        "This is a solid choice.",
        "I will be purchasing this again.",
        "Very practical and easy to use.",
        "Not impressed with the quality.",
        "This product works great for me!",
        "I wouldn’t recommend it to others.",
        "Fantastic quality and value.",
        "I’m very pleased with this purchase.",
        "The product is just okay.",
        "I had high hopes, but it fell flat.",
        "Excellent purchase, highly recommend!",
        "The performance is just average.",
        "Great product! I love it!",
        "I’m so happy with this product!",
        "This didn’t live up to the hype.",
        "It’s a good product, but I’ve seen better.",
        "Very sturdy and well-made.",
        "I had a bad experience with the delivery.",
        "This product exceeded my expectations!",
        "Great buy, would recommend!",
        "I wasn’t impressed with the quality.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "Not suitable for my needs.",
        "Great product! Highly recommend!",
        "The performance is just okay.",
        "Not what I expected at all.",
        "I’m very pleased with this purchase.",
        "This product is fantastic!",
        "Great experience overall!",
        "I would not purchase this again.",
        "This is a great product overall.",
        "Very practical and useful.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected.",
        "I’m really happy with my choice!",
        "Very convenient and easy to use.",
        "Great product! Highly recommend.",
        "It arrived quickly, which was a plus.",
        "This has become a staple in my home.",
        "I wasn’t impressed with the functionality.",
        "Very happy with the service and product.",
        "This product is fantastic!",
        "I had a bad experience with the delivery.",
        "It’s okay, but there are better options.",
        "Great for the price, very effective!",
        "I will buy this product again.",
        "It’s nice, but I wish it were bigger.",
        "The product is just okay.",
        "I had high expectations, but it fell short.",
        "Excellent purchase, very satisfied!",
        "The quality is not up to par.",
        "This is a great product overall.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected at all.",
        "I love how this product works!",
        "Great product, I use it every day.",
        "The price is a bit high for my budget.",
        "This is my new favorite item!",
        "I wouldn’t recommend this to a friend.",
        "Very useful and practical for my needs.",
        "Great purchase! Highly recommend.",
        "It arrived late, but it was worth the wait.",
        "This product is just what I needed.",
        "It’s okay, but not the best.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "The customer service was excellent.",
        "I had high hopes, but this product did not deliver.",
        "Great features and very functional.",
        "I was surprised by the quality!",
        "Not as good as I thought it would be.",
        "This is an excellent product, highly recommended.",
        "Very convenient, I use it daily.",
        "I’m not impressed with the performance.",
        "Fantastic product! I’ll buy again.",
        "It’s just okay, nothing special.",
        "Very sturdy and well made.",
        "Great quality and design!",
        "I’m really happy with my purchase.",
        "This product is worth the investment.",
        "I wouldn’t buy this again.",
        "Great value for the price!",
        "I’ve seen better products for less money.",
        "Amazing product! Highly recommended.",
        "Not worth the hype.",
        "Very satisfied with this purchase!",
        "This product is just what I was looking for.",
        "It’s not the best but it gets the job done.",
        "I love the design and functionality.",
        "It’s okay, but not my favorite.",
        "I will definitely buy this again!",
        "Not what I expected.",
        "I’m very happy with this item.",
        "Great performance and quality!",
        "I had an issue, but it was resolved quickly.",
        "This product exceeded my expectations!",
        "Very functional and easy to use.",
        "The color is different from what I expected.",
        "I’m disappointed with the quality.",
        "This is a great product for the price!",
        "I wish it had more features.",
        "Great experience overall!",
        "I would recommend this to others.",
        "Fantastic product! Highly recommend.",
        "It didn’t live up to the reviews.",
        "I had a great experience with this product.",
        "The instructions were confusing.",
        "This is an excellent purchase!",
        "Not a great fit for my needs.",
        "Great quality! I’m very satisfied.",
        "The performance is mediocre.",
        "I had to return it; it was defective.",
        "Very happy with my purchase.",
        "This is a fantastic product!",
        "The price is a bit steep.",
        "I’m impressed with the quality!",
        "It does not match the description.",
        "Great buy! Highly recommend.",
        "It’s okay, but I wouldn’t buy it again.",
        "I love how this works!",
        "Not what I was hoping for.",
        "Very effective and easy to use.",
        "The product looks nice, but it has flaws.",
        "I was surprised by the quality!",
        "Great value for the price!",
        "I would not purchase this again.",
        "Fantastic product! I’ll buy again.",
        "This is exactly what I needed.",
        "I had a good experience overall.",
        "The customer service was excellent!",
        "I’m not satisfied with this product.",
        "Great for the price, very effective.",
        "This is a solid choice.",
        "I will be purchasing this again.",
        "Very practical and easy to use.",
        "Not impressed with the quality.",
        "This product works great for me!",
        "I wouldn’t recommend it to others.",
        "Fantastic quality and value.",
        "I’m very pleased with this purchase.",
        "The product is just okay.",
        "I had high hopes, but it fell flat.",
        "Excellent purchase, highly recommend!",
        "The performance is just average.",
        "Great product! I love it!",
        "I’m so happy with this product!",
        "This didn’t live up to the hype.",
        "It’s a good product, but I’ve seen better.",
        "Very sturdy and well-made.",
        "I had a bad experience with the delivery.",
        "This product exceeded my expectations!",
        "Great buy, would recommend!",
        "I wasn’t impressed with the quality.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "Not suitable for my needs.",
        "Great product! Highly recommend!",
        "The performance is just okay.",
        "Not what I expected at all.",
        "I’m very pleased with this purchase.",
        "This product is fantastic!",
        "Great experience overall!",
        "I would not purchase this again.",
        "This is a great product overall.",
        "Very practical and useful.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected.",
        "I’m really happy with my choice!",
        "Very convenient and easy to use.",
        "Great product! Highly recommend.",
        "It arrived quickly, which was a plus.",
        "This has become a staple in my home.",
        "I wasn’t impressed with the functionality.",
        "Very happy with the service and product.",
        "This product is fantastic!",
        "I had a bad experience with the delivery.",
        "It’s okay, but there are better options.",
        "Great for the price, very effective!",
        "I will buy this product again.",
        "It’s nice, but I wish it were bigger.",
        "The product is just okay.",
        "I had high expectations, but it fell short.",
        "Excellent purchase, very satisfied!",
        "The quality is not up to par.",
        "This is a great product overall.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected at all.",
        "I love how this product works!",
        "Great product, I use it every day.",
        "The price is a bit high for my budget.",
        "This is my new favorite item!",
        "I wouldn’t recommend this to a friend.",
        "Very useful and practical for my needs.",
        "Great purchase! Highly recommend.",
        "It arrived late, but it was worth the wait.",
        "This product is just what I needed.",
        "It’s okay, but not the best.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "The customer service was excellent.",
        "I had high hopes, but this product did not deliver.",
        "Great features and very functional.",
        "I was surprised by the quality!",
        "Not as good as I thought it would be.",
        "This is an excellent product, highly recommended.",
        "Very convenient, I use it daily.",
        "I’m not impressed with the performance.",
        "Fantastic product! I’ll buy again.",
        "It’s just okay, nothing special.",
        "Very sturdy and well made.",
        "Great quality and design!",
        "I’m really happy with my purchase.",
        "This product is worth the investment.",
        "I wouldn’t buy this again.",
        "Great value for the price!",
        "I’ve seen better products for less money.",
        "Amazing product! Highly recommended.",
        "Not worth the hype.",
        "Very satisfied with this purchase!",
        "This product is just what I was looking for.",
        "It’s not the best but it gets the job done.",
        "I love the design and functionality.",
        "It’s okay, but not my favorite.",
        "I will definitely buy this again!",
        "Not what I expected.",
        "I’m very happy with this item.",
        "Great performance and quality!",
        "I had an issue, but it was resolved quickly.",
        "This product exceeded my expectations!",
        "Very functional and easy to use.",
        "The color is different from what I expected.",
        "I’m disappointed with the quality.",
        "This is a great product for the price!",
        "I wish it had more features.",
        "Great experience overall!",
        "I would recommend this to others.",
        "Fantastic product! Highly recommend.",
        "It didn’t live up to the reviews.",
        "I had a great experience with this product.",
        "The instructions were confusing.",
        "This is an excellent purchase!",
        "Not a great fit for my needs.",
        "Great quality! I’m very satisfied.",
        "The performance is mediocre.",
        "I had to return it; it was defective.",
        "Very happy with my purchase.",
        "This is a fantastic product!",
        "The price is a bit steep.",
        "I’m impressed with the quality!",
        "It does not match the description.",
        "Great buy! Highly recommend.",
        "It’s okay, but I wouldn’t buy it again.",
        "I love how this works!",
        "Not what I was hoping for.",
        "Very effective and easy to use.",
        "The product looks nice, but it has flaws.",
        "I was surprised by the quality!",
        "Great value for the price!",
        "I would not purchase this again.",
        "Fantastic product! I’ll buy again.",
        "This is exactly what I needed.",
        "I had a good experience overall.",
        "The customer service was excellent!",
        "I’m not satisfied with this product.",
        "Great for the price, very effective.",
        "This is a solid choice.",
        "I will be purchasing this again.",
        "Very practical and easy to use.",
        "Not impressed with the quality.",
        "This product works great for me!",
        "I wouldn’t recommend it to others.",
        "Fantastic quality and value.",
        "I’m very pleased with this purchase.",
        "The product is just okay.",
        "I had high hopes, but it fell flat.",
        "Excellent purchase, highly recommend!",
        "The performance is just average.",
        "Great product! I love it!",
        "I’m so happy with this product!",
        "This didn’t live up to the hype.",
        "It’s a good product, but I’ve seen better.",
        "Very sturdy and well-made.",
        "I had a bad experience with the delivery.",
        "This product exceeded my expectations!",
        "Great buy, would recommend!",
        "I wasn’t impressed with the quality.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "Not suitable for my needs.",
        "Great product! Highly recommend!",
        "The performance is just okay.",
        "Not what I expected at all.",
        "I’m very pleased with this purchase.",
        "This product is fantastic!",
        "Great experience overall!",
        "I would not purchase this again.",
        "This is a great product overall.",
        "Very practical and useful.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected.",
        "I’m really happy with my choice!",
        "Very convenient and easy to use.",
        "Great product! Highly recommend.",
        "It arrived quickly, which was a plus.",
        "This has become a staple in my home.",
        "I wasn’t impressed with the functionality.",
        "Very happy with the service and product.",
        "This product is fantastic!",
        "I had a bad experience with the delivery.",
        "It’s okay, but there are better options.",
        "Great for the price, very effective!",
        "I will buy this product again.",
        "It’s nice, but I wish it were bigger.",
        "The product is just okay.",
        "I had high expectations, but it fell short.",
        "Excellent purchase, very satisfied!",
        "The quality is not up to par.",
        "This is a great product overall.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected at all.",
        "I love how this product works!",
        "Great product, I use it every day.",
        "The price is a bit high for my budget.",
        "This is my new favorite item!",
        "I wouldn’t recommend this to a friend.",
        "Very useful and practical for my needs.",
        "Great purchase! Highly recommend.",
        "It arrived late, but it was worth the wait.",
        "This product is just what I needed.",
        "It’s okay, but not the best.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "The customer service was excellent.",
        "I had high hopes, but this product did not deliver.",
        "Great features and very functional.",
        "I was surprised by the quality!",
        "Not as good as I thought it would be.",
        "This is an excellent product, highly recommended.",
        "Very convenient, I use it daily.",
        "I’m not impressed with the performance.",
        "Fantastic product! I’ll buy again.",
        "It’s just okay, nothing special.",
        "Very sturdy and well made.",
        "Great quality and design!",
        "I’m really happy with my purchase.",
        "This product is worth the investment.",
        "I wouldn’t buy this again.",
        "Great value for the price!",
        "I’ve seen better products for less money.",
        "Amazing product! Highly recommended.",
        "Not worth the hype.",
        "Very satisfied with this purchase!",
        "This product is just what I was looking for.",
        "It’s not the best but it gets the job done.",
        "I love the design and functionality.",
        "It’s okay, but not my favorite.",
        "I will definitely buy this again!",
        "Not what I expected.",
        "I’m very happy with this item.",
        "Great performance and quality!",
        "I had an issue, but it was resolved quickly.",
        "This product exceeded my expectations!",
        "Very functional and easy to use.",
        "The color is different from what I expected.",
        "I’m disappointed with the quality.",
        "This is a great product for the price!",
        "I wish it had more features.",
        "Great experience overall!",
        "I would recommend this to others.",
        "Fantastic product! Highly recommend.",
        "It didn’t live up to the reviews.",
        "I had a great experience with this product.",
        "The instructions were confusing.",
        "This is an excellent purchase!",
        "Not a great fit for my needs.",
        "Great quality! I’m very satisfied.",
        "The performance is mediocre.",
        "I had to return it; it was defective.",
        "Very happy with my purchase.",
        "This is a fantastic product!",
        "The price is a bit steep.",
        "I’m impressed with the quality!",
        "It does not match the description.",
        "Great buy! Highly recommend.",
        "It’s okay, but I wouldn’t buy it again.",
        "I love how this works!",
        "Not what I was hoping for.",
        "Very effective and easy to use.",
        "The product looks nice, but it has flaws.",
        "I was surprised by the quality!",
        "Great value for the price!",
        "I would not purchase this again.",
        "Fantastic product! I’ll buy again.",
        "This is exactly what I needed.",
        "I had a good experience overall.",
        "The customer service was excellent!",
        "I’m not satisfied with this product.",
        "Great for the price, very effective.",
        "This is a solid choice.",
        "I will be purchasing this again.",
        "Very practical and easy to use.",
        "Not impressed with the quality.",
        "This product works great for me!",
        "I wouldn’t recommend it to others.",
        "Fantastic quality and value.",
        "I’m very pleased with this purchase.",
        "The product is just okay.",
        "I had high hopes, but it fell flat.",
        "Excellent purchase, highly recommend!",
        "The performance is just average.",
        "Great product! I love it!",
        "I’m so happy with this product!",
        "This didn’t live up to the hype.",
        "It’s a good product, but I’ve seen better.",
        "Very sturdy and well-made.",
        "I had a bad experience with the delivery.",
        "This product exceeded my expectations!",
        "Great buy, would recommend!",
        "I wasn’t impressed with the quality.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "Not suitable for my needs.",
        "Great product! Highly recommend!",
        "The performance is just okay.",
        "Not what I expected at all.",
        "I’m very pleased with this purchase.",
        "This product is fantastic!",
        "Great experience overall!",
        "I would not purchase this again.",
        "This is a great product overall.",
        "Very practical and useful.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected.",
        "I’m really happy with my choice!",
        "Very convenient and easy to use.",
        "Great product! Highly recommend.",
        "It arrived quickly, which was a plus.",
        "This has become a staple in my home.",
        "I wasn’t impressed with the functionality.",
        "Very happy with the service and product.",
        "This product is fantastic!",
        "I had a bad experience with the delivery.",
        "It’s okay, but there are better options.",
        "Great for the price, very effective!",
        "I will buy this product again.",
        "It’s nice, but I wish it were bigger.",
        "The product is just okay.",
        "I had high expectations, but it fell short.",
        "Excellent purchase, very satisfied!",
        "The quality is not up to par.",
        "This is a great product overall.",
        "I had a minor issue, but it was resolved quickly.",
        "Not what I expected at all.",
        "I love how this product works!",
        "Great product, I use it every day.",
        "The price is a bit high for my budget.",
        "This is my new favorite item!",
        "I wouldn’t recommend this to a friend.",
        "Very useful and practical for my needs.",
        "Great purchase! Highly recommend.",
        "It arrived late, but it was worth the wait.",
        "This product is just what I needed.",
        "It’s okay, but not the best.",
        "Fantastic! I love this product.",
        "I’m very satisfied with my order.",
        "The customer service was excellent.",
        "I had high hopes, but this product did not deliver.",
        "Great features and very functional.",
        "I was surprised by the quality!",
        "Not as good as I thought it would be.",
        "This is an excellent product, highly recommended.",
        "Very convenient, I use it daily.",
        "I’m not impressed with the performance.",
        "Fantastic product! I’ll buy again.",
        "It’s just okay, nothing special.",
        "Very sturdy and well made.",
        "Great quality and design!",
        "I’m really happy with my purchase.",
        "This product is worth the investment.",
        "I wouldn’t buy this again.",
        "Great value for the price!",
        "I’ve seen better products for less money.",
        "Amazing product! Highly recommended.",
        "Not worth the hype.",
        "Very satisfied with this purchase!",
        "This product is just what I was looking for.",
        "It’s not the best but it gets the job done.",
        "I love the design and functionality.",
        "It’s okay, but not my favorite.",
        "I will definitely buy this again!",
        "Not what I expected.",
        "I’m very happy with this item.",
        "Great performance and quality!",
        "I had an issue, but it was resolved quickly.",
        "This product exceeded my expectations!",
        "Very functional and easy to use.",
        "The color is different from what I expected.",
        "I’m disappointed with the quality.",
        "This is a great product for the price!",
        "I wish it had more features.",
        "Great experience overall!",
        "I would recommend this to others.",
        "Fantastic product! Highly recommend.",
        "It didn’t live up to the reviews.",
        "I had a great experience with this product.",
        "The instructions were confusing.",
        "This is an excellent purchase!",
        "Not a great fit for my needs.",
        "Great quality! I’m very satisfied.",
        "The performance is mediocre.",
        "I had to return it; it was defective.",
        "Very happy with my purchase.",
        "This is a fantastic product!",
        "The price is a bit steep.",
        "I’m impressed with the quality!",
        "It does not match the description.",
        "Great buy! Highly recommend.",
        "It’s okay, but I wouldn’t buy it again.",
        "I love how this works!",
        "Not what I was hoping for.",
        "Very effective and easy to use.",
        "The product looks nice, but it has flaws.",
        "I was surprised by the quality!",
        "Great value for the price!",
        "I would not purchase this again.",
        "Fantastic product! I’ll buy again.",
        "This is exactly what I needed.",
    ];
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'id' => (string) Str::uuid(), // Generate a UUID for the id
            'user_name' => $this->faker->name,
            'review_text' => $this->faker->randomElement($this->sampleReviews), // Use a random review from the array
            'created_at' => now(),
            'updated_at' => now(),
        ];
    }
}
