<?php

namespace App\Http\Controllers\AdminControllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\Catgory\StoreCategoryRequest;
use App\Http\Requests\Catgory\UpdateCategoryRequest;
use App\Models\Category;
 

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        // Fetch all categories from the database
        $categories = Category::latest()->paginate(10); // Paginate with 10 items per page

        // Return the view and pass the data
        return view('AdminPages.Category.index', compact('categories'));
    }


    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request)
    {
        // Use the validated data from the request
        $validatedData = $request->validated();
    
        // Create a new category. The slug is automatically generated by the model.
        Category::create([
            'name' => $validatedData['name'],
            'type' => $validatedData['type'],
            'description' => $validatedData['description'],
            'status' => $validatedData['status'],
        ]);
    
        // Redirect to the category index page with a success message
        return redirect()->route('categories.index')
            ->with('success', 'Category added successfully!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->update($request->validated());

        // Redirect back with a success message
        return redirect()->route('categories.index')->with('success', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('categories.index')
            ->with('success', 'Category deleted successfully!');
    }
}
